touch up

diff --git a/github-backup b/github-backup
--- a/github-backup
+++ b/github-backup
@@ -25,8 +25,8 @@ if [[ -z $user ]]; then
 fi
 
 # Check for jsontool
-if ! json --version &>/dev/null; then
-	echo 'Dependency "json" not found. Install with `npm install -g jsontool`'
+if ! jq --version &>/dev/null; then
+	echo 'Dependency "jq" not found.'
 	exit 2
 fi
 
@@ -41,14 +41,14 @@ while true; do
 	_repos=$(curl -sS "$api/users/$user/repos?per_page=$per_page&page=$i")
 
 	# Check for error
-	if [[ -z $_repos || -n "$(json message <<< "$_repos")" ]]; then
+	if [[ -z $_repos || -n "$(jq -r .message <<< "$_repos" 2>/dev/null)" ]]; then
 		echo 'Error pulling repo!' >&2
 		echo "$_repos" >&2
 		exit 4
 	fi
 
 	# get the field we care about
-	_repos=$(json -a git_url <<< "$_repos")
+	_repos=$(jq -r '.[].clone_url' <<< "$_repos")
 
 	# Append the fields
 	repos=$repos$_repos$'\n'
